return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	config = function()
		local logo = {
			"",
			"",
			"   ██████╗  ██████╗ ██╗    ██╗███████╗██████╗     ███╗   ██╗██╗   ██╗██╗███╗   ███╗",
			"   ██╔══██╗██╔═══██╗██║    ██║██╔════╝██╔══██╗    ████╗  ██║██║   ██║██║████╗ ████║",
			"   ██████╔╝██║   ██║██║ █╗ ██║█████╗  ██████╔╝    ██╔██╗ ██║██║   ██║██║██╔████╔██║",
			"   ██╔═══╝ ██║   ██║██║███╗██║██╔══╝  ██╔══██╗    ██║╚██╗██║╚██╗ ██╔╝██║██║╚██╔╝██║",
			"   ██║     ╚██████╔╝╚███╔███╔╝███████╗██║  ██║    ██║ ╚████║ ╚████╔╝ ██║██║ ╚═╝ ██║",
			"   ╚═╝      ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝    ╚═╝  ╚═══╝  ╚═══╝  ╚═╝╚═╝     ╚═╝",
			"",
			"",
		}
		require("dashboard").setup({
			theme = "doom",
			config = {
				header = logo,
				center = {
					{ icon = "  ", desc = "New File", action = "ene | startinsert", key = "n" },
					{ icon = "  ", desc = "Find File", action = "Telescope find_files", key = "f" },
					{ icon = "  ", desc = "Recent Files", action = "Telescope oldfiles", key = "r" },
					{ icon = "  ", desc = "Find Word", action = "Telescope live_grep", key = "g" },
					{ icon = "  ", desc = "Edit Config", action = "edit ~/.config/nvim/init.lua", key = "c" },
					{ icon = "  ", desc = "Quit", action = "qa", key = "q" },
				},
				footer = function()
					local fortune = {
						"🧪 Debugging: the art of removing the needles from the haystack",
						"🎢 Your Neovim setup is smoother than a rollercoaster ride",
						"📦 Packed with plugins, powered by passion",
						"🛸 Alien tech? No, just Neovim with a good config",
						"🔌 You’ve plugged into productivity",
						"💾 Remember: :w is love, :w is life",
						"🎉 You opened Neovim. That's already a win.",
						"🔍 LSPs are watching your back",
						"🛠️ Crafting code like a digital blacksmith",
						"🎬 Lights, camera, :make!",
						"🧃 Juice up your dev flow — Neovim style",
						"🧱 Building one buffer at a time",
						"📚 Learning Vim never ends, but you’re leveling up",
						"🧭 Lost in code? Let Neovim be your compass",
						"🌀 Insert mode? More like inspiration mode",
						"🧵 Threads of logic woven into your keystrokes",
						"🚦 Green light: you may code now",
						"🖖 Live long and :source your config",
						"📈 Today’s forecast: 100% chance of clean commits",
						"🪐 Your code just entered orbit",
						"👣 Step by step, buffer by buffer",
						"⚙️ Tweak, test, triumph — the Neovim way",
						"🧊 Ice cold precision in every motion",
						"🧃 Plugin manager hydrated and healthy",
						"🧙♂️ May the macros be ever in your favor",
						"🎇 Your brain and Neovim: a fireworks display of efficiency",
						"🪫 Remember to stretch — even modal editing needs a break",
						"🚧 Code in progress — brilliance under construction",
						"🧼 :wq with satisfaction",
						"📐 Aligning code and cosmos with Neovim",
						"✨ Neovim > VSCode ✨",
						"🚀 Ready to build something cool!",
						"💡 Tip: Use <leader>tt to run tests!",
						"🐢 Slow and steady... or not. Let's go!",
						"⚡ With great power comes great productivity",
						"🧠 You're now using 100% of your brain capacity",
						"🔥 Your code is on fire today! (In a good way)",
						"🌈 Colors aren't just for terminals, they're for life",
						"🦄 Neovim: Making the impossible merely difficult since 2014",
						"🧙 You're a wizard, Harry! And by Harry, I mean you!",
						"🪄 Abracadabra! Your cursor moved exactly where you wanted it",
						"🐱 If cats used text editors, they'd use Neovim",
						"🌟 You're not just coding, you're crafting digital art",
						"🦊 Quick like a fox, smart like... well, a fox using Neovim",
						"🐧 Linux + Neovim = Match made in heaven",
						"🔮 I see efficient coding in your future",
						"💻 Your computer feels honored to run Neovim",
						"🤖 Robots dream of electric Neovim sessions",
						"🎯 Your precision with Neovim commands is uncanny",
						"🎨 Painting with keystrokes, one character at a time",
						"⏱️ Time flies when you're having fun with modal editing",
						"🌠 Wish upon a star, but code with Neovim",
						"🧠 Big brain energy detected in this Neovim session",
						"📊 9/10 developers recommend Neovim for their colleagues",
						"🍕 Code is like pizza: even when it's bad, it's still pretty good",
						"🎸 Neovim: the rock star of text editors",
						"🏆 Achievement unlocked: Started Neovim today!",
						"🔍 Searching with telescope: like finding a needle in a haystack, but instant",
						"🎭 Vim or Neovim? Why not both? (But really, Neovim)",
						"🦉 Night coding wisdom: Save often, commit more often",
						"🚴 Navigating code with Neovim is like riding a bike downhill - WHEEEEE!",
						"🧘 Find your zen in the perfect keybinding",
						"☕ Coffee + Neovim = Unstoppable",
						"🌱 Growing your Neovim config like a beautiful garden",
						"🧩 Your plugins fit together perfectly, like a well-designed puzzle",
						"🚀 To infinity and beyond! (Or at least to the end of this file)",
						"🌊 Riding the wave of productivity with Neovim",
						"🔧 Configured to perfection, ready for action",
						"🏹 Your keystrokes hit the target every time",
						"🎹 Your keyboard is your instrument, Neovim is your symphony",
						"🌄 Another day, another opportunity to use Neovim",
					}
					math.randomseed(os.time())
					return { fortune[math.random(#fortune)] }
				end,
			},
		})
	end,
}
